/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-WWZ3BnTP72-D6EM7A2kXashcdVvRD197xl-4y6FQOYf1WhPNIuWK05GlaLe0Ph0IcY3eU8qekyor-ltJpS06XXkLdLl9W3Tu6rIOwItfgaj-vyYhRxMJzIub",
  "tt": "tt-1-NXP5HEQAelhU07twbZXhjVmMoYkcmP6Fj5pSK1iqcJw=",
  "version": "2020-11-20"
}

export default ebconfig;